puts "Destroying previous stuff"

PostTag.destroy_all
UserTag.destroy_all
PostSaved.destroy_all
PostUpvoted.destroy_all
Contact.destroy_all
Post.destroy_all
Tag.destroy_all
User.destroy_all

puts "Old stuff destroyed successfully"
puts "Adding new stuff"

#TAG SEEDS
tag1 = Tag.create(name:"💰 business", category:"business")
tag2 = Tag.create(name:"📡 technology", category:"technology")
tag3 = Tag.create(name:"📈 finance", category:"finance")
tag4 = Tag.create(name:"🤹 entrepreneurship", category:"entrepreneurship")
tag5 = Tag.create(name:"🧬 sciences", category:"sciences")
tag6 = Tag.create(name:"🎭 psychology", category:"psychology")
tag7 = Tag.create(name:"👓 sociology", category:"sociology")
tag8 = Tag.create(name:"🧞‍♂️ philosophy", category:"philosophy")
tag9 = Tag.create(name:"⚖️ politics", category:"politics")
tag10 = Tag.create(name:"🥦 health", category:"health")


#USER SEEDS + AVATAR
#romain = User.new(email: "romain@guilde.com", first_name: 'Romain', last_name: 'Losey', bio: 'Busy building a life I do not need to escape from', contact_text: 'Please reach out to me on LinkedIn: https://www.linkedin.com/in/romain-losey/' , password: '12345678', password_confirmation: '12345678')
#romain.photo.attach(io: URI.open('https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1624455076/taxkkidiqfgsoecqktb3.jpg'), filename: 'profile.jpg', content_type: 'image/jpg')
#romain.save!

marc = User.new(email: "marc@guilde.com", first_name: 'Marc', last_name: "L'Eplattenier", bio: 'Busy building a life I do not need to escape from', contact_text: 'Please reach out to me on LinkedIn: https://www.linkedin.com/in/mleplattenier/', password: '12345678', password_confirmation: '12345678')
marc.photo.attach(io: URI.open('https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1624023909/wfliysfgym33qlzi0dsd.jpg'), filename: 'profile.jpg', content_type: 'image/jpg')
marc.save!

nico = User.new(email: "nico@guilde.com", first_name: 'Nicholas', last_name: 'Martin', bio: 'You miss 100% of the shots you don’t take', contact_text: 'Please reach out to me on LinkedIn: https://www.linkedin.com/in/nicholas-martin-777471203/', password: '12345678', password_confirmation: '12345678')
nico.photo.attach(io: URI.open('https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1624437133/tppabzxei90i8j8joyps.jpg'), filename: 'profile.jpg', content_type: 'image/jpg')
nico.save!

nathan = User.new(email: "nathan@guilde.com", first_name: 'Nathan', last_name: 'Cohen', bio: 'Exploring space with my amazing coding buddies', contact_text: 'Please reach out to me on LinkedIn: https://www.linkedin.com/in/nathan-cohen-b7aa651a1/', password: '12345678', password_confirmation: '12345678')
nathan.photo.attach(io: URI.open('https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1624987859/tr4zygrx5akfawfoh4vj.jpg'), filename: 'profile.jpg', content_type: 'image/jpg')
nathan.save!



#USER_TAGS SEEDS
#romain.tags << [tag1, tag2]
#romain.save

marc.tags << [tag2, tag8]
marc.save

nico.tags << [tag4, tag9]
nico.save

nathan.tags << [tag2, tag4]
nathan.save

#USER_CONTACTS SEEDS
# FOLLOWER = FOLLOWED (=> User.followers = list of users who follow User)
# FOLLOWING = FOLLOWING (=> User.followings = list of users who are followed by User)
#contact1 = Contact.create(follower: romain, following: marc)
contact2 = Contact.create(follower: nathan, following: nico)
contact3 = Contact.create(follower: nico, following: nathan)
contact4 = Contact.create(follower: nathan, following: marc)

#POST SEEDS
business1 = Post.new(title: "Tim Cook’s decade at Apple makes him the most successful successor CEO ever",
		description: "Dedication, attention to detail and an instinct to do the opposite of what Steve Jobs might have done earn him that accolade",
		text_action_text: "THE TECHNOLOGY industry is littered with managers who have tried and failed to emulate successful founders. Think of <em>Steve Ballmer</em>, who succeeded Bill Gates at Microsoft, and Kevin Rollins, who took over from Michael Dell at Dell Technologies, who returned a few years later. Tim Cook heads the list of exceptions. Since he took the helm of Apple from Steve Jobs ten years ago, the firm’s market capitalisation has increased by more than $2trn. <strong>NO CHIEF EXECUTIVE</strong>&nbsp;in history has created as much total shareholder value. Mr Cook’s numbers beat the value generated by Jeff Bezos, who retired as Amazon’s chief executive in July, over his 24 years in charge. They also surpass the achievement of Warren Buffett, who has been running Berkshire Hathaway for nearly 45 years. During his second almost 14-year stint at Apple, Jobs added only $343.6bn to the firm’s market valuation, or $24.7bn a year.",
		user: nico)
business1.photo.attach(io: URI.open('https://www.mactrast.com/wp-content/uploads/2019/03/D2AE21F6-CE02-4E42-B5A2-5F49901F5FCA-800x457.jpeg'), filename: 'business1.jpg' , content_type: 'image/jpg')
business1.save!

philosophy1 = Post.new(title: "You are Not Lazy or Undisciplined. You Have Internal Resistance.",
		description: "Why you can’t just do it, and what to do instead",
		text_action_text: "When I was writing my PhD I didn’t have bad weeks. I had bad months. The kind when each day you wake up thinking, “Today I will actually do the thing” and then you… don’t. Somehow the day ticks by and then it’s 11 pm and you still haven’t done the thing and it feels like you might as well go to bed and start over tomorrow, but already you have a sinking horrible sense that you won’t do it then either. And lo, the cycle repeats.",
		user: nico)
philosophy1.photo.attach(io: URI.open('https://i.imgflip.com/2qtvhx.jpg'), filename: 'philosophy1.jpg' , content_type: 'image/jpg')
philosophy1.save!

health1 = Post.new(title: "I cut my body fat percentage almost in half after starting a high-protein diet. Here’s what I eat.",
		description: "My body fat from 30% to 17% by eating a high-protein diet comprised of chicken, turkey, and Greek yogurt.",
		text_action_text: "One of the secrets to successful weight loss is to kick-start our metabolism as soon as possible after we wake. The best way to do that is to eat breakfast. In fact, nothing, including <a>exercise</a>, gets our metabolism going as fast again after eight hours of restful sleep as eating a healthy breakfast!<br><br>When we skip breakfast, not only does our metabolic rate stay low, so too does our blood sugar levels. Low blood sugar levels resulting from missing breakfast often leads us to feel lethargic.<br><br>Low blood sugar levels in the morning eventually make us feel extra hungry later, which sets us up for impulse snacking, or eating overly large portions of food at lunch and dinner.<br><br>When we eat breakfast, our body feels nourished and satisfied, making us far less likely to over eat during the rest of the day.",
		user: nico)
health1.photo.attach(io: URI.open('https://nexter.org/wp-content/uploads/2019/03/diet-weight-loss-memes-pic1.jpg'), filename: 'health1.jpg' , content_type: 'image/jpg')
health1.save!

tech1 = Post.new(title: "If software engineering is in demand, why is it so hard to get a software engineering job?",
		description: "The demanding environment isn't always attrative for some.",
		text_action_text: "There are lots of “opening strategies” you may follow. Maybe a company’s HR reaches out to you first on LinkedIn; maybe you choose to trust a third party recruiter. Your mileage may vary with third party recruiters (also referred to as “head hunters”), but to put it bluntly, there is a reason they have such a bad reputation. Some of them are really, really bad. The bad ones will try to set you up with a company that is not a good fit, they will “shotgun blast” requests to anyone and everyone, and they will not have your best interest in mind. What they want from the arrangement is money.<br>…Though, to be fair, that is probably also what you want.<br>Maybe you decide to reach out to a friend instead. Maybe you reach out to HR departments directly, or you decide to do what a zillion other people are doing and just try to indeed-easy-apply your way to success.There are a <em>lot</em> of tech companies trying to make it right now, and some of them are pretty random. One company was delivering medical supplies via tiny drones. One company was trying to disrupt healthcare by making customers pay hundreds of dollars every month to see more doctors. The weirdest company I have ever interacted with was building a dating app…as if people would <em>pay</em> for an app where you swiped right to determine potential matches.",
		user: nico)
tech1.photo.attach(io: URI.open('https://i.pinimg.com/736x/4b/b2/20/4bb220922895dd28412188de0ce6abb4.jpg'), filename: 'tech1.jpg' , content_type: 'image/jpg')
tech1.save!

finance1 = Post.new(title: "What are the most important things to know about personal finance?",
		description: "In the ever-evolving environment of finance, things are getting more and more complicated",
		text_action_text: "Strive towards assets based living from income based living.<br>Let me explain this a bit more.When you first graduate from a school/college and get your first job, you are essentially living off your income. The monthly pay checks you get will help you pay your bills and past debts.<br>&nbsp;Now is the choice you need to make, should I continue to live off my income and hope that income rise would continue well beyond mid to later years of my career to continue enhance my quality of life, or should I try to accumulate assets which will pay off my future ambitions whether my job meets my financial expectations or not. In today’s uncertain times, it has become ever more important to have more than decent savings which can help you maintain same quality of life, help you reduce your debts and also be certain about your and your family’s future, like saving for your children’s education. You can achieve this is by accumulating assets right at the start. However first thing is to correctly identify what is an asset. Asset is something tangible or otherwise which will cause net cash flow to you in future. So a fancy car, watch, phone etc are really not assets. Also when accumulating assets, you should keep in mind to not accumulate something which is speculative in nature and only way you can get some cashflow is by selling the same.",
		user: nico)
finance1.photo.attach(io: URI.open('https://i.imgur.com/itWHhbH.png'), filename: 'finance1.jpg' , content_type: 'image/jpg')
finance1.save!

philo2 = Post.new(title: "What is the most important question one has to ask oneself?",
		description: "Not always easy to find the answer",
		text_action_text: "The most interesting question someone ever had me pose myself was my therapist in New Zealand when I went through a rough patch and was very unhappy.<br>&nbsp;It was a seemingly childish question, but boy, the power it unleashes! Here it is:<br>&nbsp;<em>“If you were so rich that you didn’t need to work anymore, what would you do?”</em><br> It hit me like a ton of bricks that basically my entire life and almost all the choices I made were compromises in order to survive financially, and when we’re honest, it’s true for most of us. Where we live, how we live, what we do, what we drive, where we travel, what we eat, how we decorate our homes, what we do for fun… it’s endless, the distortions and ripples financially motivated choices put into our existence.<br> Answering this question truthfully, at length, and in detail, is not easy at all, but it will eventually reveal your true self, and give you a different vision of what it is that you truly want in life. In case anyone wonders how I answered it for myself, I said I’d want to be a local writer who drinks too much, and lives in western Argentina. I would live in some shabby chic old character villa surrounded by vineyards, with a dusty road leading up to it. The place would be crawling with cats, and I’d be driving an old Dodge 3700 GT. Midnight blue.<br>Yes, I would still write, even if I weren’t paid for it. I do now, too, as you may have noticed.",
		user: nico)
philo2.photo.attach(io: URI.open('https://s.yimg.com/ny/api/res/1.2/8BB7bb_.XU9F3S47PlwZEg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTY0MDtoPTY0MA--/https://media.zenfs.com/en-US/the_mighty_beauty_225/6db682d07916ca6e6c8073a1dd4033ba'), filename: 'philo2.jpg' , content_type: 'image/jpg')
philo2.save!

science1 = Post.new(title: "Measuring a black hole’s mass isn’t easy",
		description: "A new technique will change this though",
		text_action_text: "An actively feeding black hole surrounds itself with a disk of hot gas and dust that flickers like a campfire. Astronomers have now found that monitoring changes in those flickers can reveal something that is notoriously hard to measure: the behemoth’s heft.<br>“It’s a new way to weigh black holes,” says astronomer Colin Burke of the University of Illinois at Urbana-Champaign. What’s more, the method could be used on <a>any astrophysical object with an accretion disk</a>, and may even help find elusive midsize black holes, researchers report in the Aug. 13 <em>Science</em>.<br>It’s not easy to measure a black hole’s mass. For one thing, the dark behemoths are notoriously difficult to see. But sometimes black holes reveal themselves when they eat. As gas and dust falls into a black hole, the material organizes into a disk that is heated to white-hot temperatures and can, in some cases, outshine all the stars in the galaxy combined.<br>Measuring the black hole’s diameter can reveal its mass using Einstein’s general theory of relativity. But only the globe-spanning Event Horizon Telescope has made this sort of measurement, and <a>for only one black hole</a> so far (<em>SN: 4/22/19</em>). Other black holes have been weighed via observations of their influence on the material around them, but that takes a lot of data and doesn’t work for every supermassive black hole.So, looking for another way, Burke and colleagues turned to accretion disks. Astronomers aren’t sure how black holes’ disks flicker, but it seems like small changes in light combine to brighten or dim the entire disk over a given span of time. Previous research had hinted that the time it takes a disk to fade, brighten and fade again is related to the mass of its central black hole. But those claims were controversial, and didn’t cover the full range of black hole masses, Burke says.<br>So he and colleagues assembled observations of 67 actively feeding black holes with known masses. The behemoths spanned sizes from 10,000 to 10 billion solar masses. For the smallest of these black holes, the flickers changed on timescales of hours to weeks. Supermassive black holes with masses between 100 million and 10 billion solar masses flickered more slowly, every few hundred days.<br>“That gives us a hint that, okay, if this relation holds for small supermassive black holes and big ones, maybe it’s sort of a universal feature,” Burke says.",
		user: nico)
science1.photo.attach(io: URI.open('https://static.boredpanda.com/blog/wp-content/uploads/2019/04/10-5caf31e692bae__700.jpg'), filename: 'science1.jpg' , content_type: 'image/jpg')
science1.save!

psycho1 = Post.new(title: "Which MBTI personality type is the most complex to understand?",
		description: "This isn't as easy as you might think",
		text_action_text: "So I want to make sure I don’t misunderstand the question. I see two primary ways to interpret this question and I’ll address each separately. If this is what it means to be misunderstood, then take your pick of the INxx’s. All 4 of these types, on average, go through long, intense periods of their early lives feeling completely misunderstood, lonely, and ostracized.<br>&nbsp;Out of all four INxx types, INTPs probably have the most difficult time getting over this, as they’re the least social of all 16 types, Fe-inferiors, etc. The biggest enemy of INTPs is stagnation. The whole cliche of the nerd that sits in a basement playing video games all day is born out of an actual psychology of stagnant, socially anxious INTPs that find nothing in the world really worth their efforts. I’ve personally been there. That type of person suffers from a lot of judgment from themselves and others, and naturally will go long stretches of time feeling misunderstood because they’re doing nothing to connect with people in the first place.<br>&nbsp;The most intense feelings of feeling misunderstood probably are experienced by INFPs, as they often harbor deep fears surrounding their identity and authenticity. The great journey for INFPs is coming out and expressing themselves fully no matter how big of weirdos others wind up thinking they are. INFPs that don’t wind up hiding and feeling extremely misunderstood as they repress their identity out of fear.<br>2. Misunderstood means “other people have trouble following their thinking processes.”<br>&nbsp;INxJs here, probably especially INFJs. Ni (introverted intuition) is the primary brain function that these types use, and it can be hard to follow. Ni makes unconscious leaps in its thought patterns. The way Ni basically works is that it (unconsciously) observes a repeated sequence of thoughts",
		user: nico)
psycho1.photo.attach(io: URI.open('https://64.media.tumblr.com/75940d72a5faf1587e4af3aa3a471ae6/tumblr_pet6xuwlgx1v34reg_1280.jpg'), filename: 'psycho1.jpg' , content_type: 'image/jpg')
psycho1.save!

philo3 = Post.new(title: "The Most Important Ritual You Can Practice This Year",
		description: "Why did Marcus Aurelius spend those precious hours in his tent, writing by the lamplight, even on the nights and mornings he strained under the burdens of his war-time duties? It wasn’t for our benefit.",
		text_action_text: "Why did <a>Marcus Aurelius</a> spend those precious hours in his tent, writing by the lamplight, even on the nights and mornings he strained under the burdens of his war-time duties? It wasn’t for our benefit. No, he never expected <a><em>Meditations</em></a> would see an audience. He was writing for himself, <em>to</em> himself, as a way to practice the principles of the philosophy we are still following today. He was journaling as a means of self-improvement as much as he was of self-expression.<br><a>As Tim Ferriss has said of his daily journaling habit</a>, “I don’t journal to ‘be productive.’ I don’t do it to find great ideas, or to put down prose I can later publish. The pages aren’t intended for anyone but me…I’m trying to figure things out…I’m just caging my monkey mind on paper so I can get on with my fucking day.”",
		user: nico)
philo3.photo.attach(io: URI.open('https://i.chzbgr.com/full/9387061248/h2E90A2B9/funny-ok-boomer-meme-from-ancient-greece'), filename: 'philo3.jpg' , content_type: 'image/jpg')
philo3.save!

health2 = Post.new(title: "Training at the Gym, Training for Life: Creating Better Versions of the Self Through Exercise",
		description: "The present study draws on Scott’s (2011) notion of the Re-Inventive Institution and explores how gym members make sense and give meaning to their exercise regime",
		text_action_text: "Whether in the basement of a commercial complex, half-hidden between two corner stores, next to the tube station or on a wide green field in the suburbs, gyms have conquered urban space. Every European and North American city, and even small towns, seem to have a fitness gym. Gyms are one of the most pursued leisure places in Western societies and can be said to have established themselves as part of a white, middle-class culture.<br>&nbsp;In the UK, for example, almost 13% of the UK population is registered as members of a private health and fitness gym or a publicly-owned fitness facility, with London having the most registered users<br>Fitness gyms vary in location, membership fees and serve different social and economic milieus. Most urban gyms are located in the city centre and are at their busiest during lunch time and after work hours. In order to attract customers, most gyms offer more than a plain and functional working out environment but present themselves as lifestyle or family oriented places. Depending on the size and the target group, multi-purpose amenities encourage pre- or post-training activities, for example at their spas and beauty centres or they organize social activities at the weekend.<br>&nbsp;As notes, “hybrid consumption”, that is, consumption of several goods and services within one single place, tends to extend the time spent by the customers there. Consequently, one may think that the more time gym users spend at their gym, the more they engage with its material and social environment, and the more they are affected by the same so that the gym becomes more than just a training site for them.",
		user: nico)
health2.photo.attach(io: URI.open('https://incredibleshrinkingbeardedman.files.wordpress.com/2019/07/34fd2387e6af2665b783af455966de2a.jpg'), filename: 'health2.jpg' , content_type: 'image/jpg')
health2.save!

entrepreneur1 = Post.new(title: "Why the Lean Start-Up Changes Everything",
		description: "Launching a new enterprise—whether it’s a tech start-up, a small business, or an initiative within a large corporation—has always been a hit-or-miss proposition.",
		text_action_text: "Launching a new enterprise—whether it’s a tech start-up, a small business, or an initiative within a large corporation—has always been a hit-or-miss proposition. According to the decades-old formula, you write a business plan, pitch it to investors, assemble a team, introduce a product, and start selling as hard as you can. And somewhere in this sequence of events, you’ll probably suffer a fatal setback. The odds are not with you: As new research by Harvard Business School’s Shikhar Ghosh shows, 75% of all start-ups fail.<br>But recently an important countervailing force has emerged, one that can make the process of starting a company less risky. It’s a methodology called the “lean start-up,” and it favors experimentation over elaborate planning, customer feedback over intuition, and iterative design over traditional “big design up front” development. Although the methodology is just a few years old, its concepts—such as “minimum viable product” and “pivoting”—have quickly taken root in the start-up world, and business schools have already begun adapting their curricula to teach them.",
		user: nico)
entrepreneur1.photo.attach(io: URI.open('https://iq.opengenus.org/content/images/2019/12/tesla_1.png'), filename: 'entrepreneur.jpg' , content_type: 'image/jpg')
entrepreneur1.save!

socio1 = Post.new(title: "How will society keep human labor relevant in an era of increasing automation?",
		description: "AI is changing the game",
		text_action_text: "People have been asking this question since the beginning of the industrial revolution.<br>&nbsp;In the early 1800's the Luddites were protesting against mechanisation of the textile industry in England. Textiles were an important part of the UK economy and a major employer, so if even half of these jobs were lost there would be serious problems of unemployment and underemployment. The Luddites could not comprehend that the labour thus freed up would then be available to newly emerging industries, many of which didn't exist yet. A generation later, Britain was building the world's first railway network and ushering in a new age of transportation.<br>&nbsp;This is what progress looks like. You start from a position where fulfilling basic needs is labour intensive and you figure out how to meet those needs with less effort, following which labour and capital can move into new arenas. In a primitive economy nearly 100% of the population will be occupied producing food. After they mechanise agriculture, labour moves into manufacturing. When a small proportion of the workforce can produce all the cars and TVs you need, opportunities arise in service provision. As services become automated new services are invented. Two centuries of intensive automation and mechanisation has not led to high unemployment in developed countries.<br>People will always want other people to do things for them. As basic needs are met more and more easily, new ways of encouraging people to part with their money will be devised. Instead of ploughing fields, today's resources are increasingly devoted to areas such as healthcare.Where unemployment is high it is not because of automation, it is because of a failure of the financial system to provide capital to where it can be used to good effect. And ultimately capitalists don't like workers to be idle, because the unemployed don't consume as many of their products.<br>&nbsp;Of course, capitalism is not the only game in town. Marx had plenty of ideas about what automation meant and his view was that it would lead to super-abundance, a world in which capitalism became unnecessary. If you accept his analysis then automation is unequivocally good, as it leads more quickly to a situation where all of our needs are met and we can continue to the logical end-point of our societal development.<br>&nbsp;Either way, automation is not a threat to us. Either it lets us discover new industries and opportunities or it brings forward a time when we can retire in a communist utopia. What it won't do is lead to a situation where a few capitalists own all the machines and everyone else has nothing, because that is not a sustainable outcome.",
		user: nico)
socio1.photo.attach(io: URI.open('https://media-exp1.licdn.com/dms/image/C4E12AQE0TAMpLO1L4A/article-inline_image-shrink_1000_1488/0/1524167545936?e=1632960000&v=beta&t=YZdHeYEUeLokx1yEUi10vbFsUnt0qgFnvSNUwzZ05cE'), filename: 'socio1.jpg' , content_type: 'image/jpg')
socio1.save!

business2 = Post.new(title: "The Best Business Blogs Every Entrepreneur Should Be Reading",
		description: "On the internet, an endless source of industry insights, news and tips are at your fingertips - but how do you know which are worth reading? Here are the top business blogs every entrepreneur should stay on top of.",
		text_action_text: "1. <a>Mashable Business</a> is a one-stop shop for any online entrepreneur. We check it every morning to get our daily dose of what's trending in the digital world. Just try not to let yourself get distracted by all the fun 'watercooler' type pieces in the sidebar - stick to the business portion of the blog.2. <a>Fast Company</a><br>Not only is <a>Fast Company</a>'s blog incredibly visually appealing, it's also mentally appealing. Its creative, compelling articles and case studies are wonderful ways to learn about entrepreneurship, design, technology trends, industry influencers, and so much more.3. <a>Forbes: Entrepreneurs</a><br>Forbes describes itself as 'a leading source for reliable business news and financial information' and Forbes' Entrepreneurs section is a leading source for reliable business news and financial information for – you guessed it – entrepreneurs and small business owners. Once you get past the annoying pop-up screens, their blog has some top-quality content.",
		user: nico)
business2.photo.attach(io: URI.open('https://miro.medium.com/max/1000/1*qVGmZn-3Npku-1qdU4-KHg.jpeg'), filename: 'business2.jpg' , content_type: 'image/jpg')
business2.save!




#POST TAGS SEEDS
business1.tags << [tag1]
business1.save

philosophy1.tags << [tag8]
philosophy1.save

health1.tags << [tag10]
health1.save

tech1.tags << [tag2]
tech1.save

finance1.tags << [tag3]
finance1.save

philo2.tags << [tag8]
philo2.save

science1.tags << [tag5]
science1.save

psycho1.tags << [tag6]
psycho1.save

philo3.tags << [tag8, tag6]
philo3.save

health2.tags << [tag10]
health2.save

entrepreneur1.tags << [tag4]
entrepreneur1.save

socio1.tags << [tag7]
socio1.save

business2.tags << [tag1, tag4]
business2.save

puts "New stuff added successfully"
